<?php

namespace ActualiteBundle\Repository;

/**
 * ActualiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActualiteRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAllActualites($recherche = null, $categorie = null, $admin = false)
    {
        $qb = $this->createQueryBuilder('a');

        /**
         * recherche via le titre
         */
        if(!is_null($recherche)){
            $qb->andWhere('a.titre LIKE :recherche')
               ->setParameter('recherche', '%'.$recherche.'%');
        }

        /**
         * recherche via la catégorie
         */
        if(!is_null($recherche)){
            $qb->andWhere('a.categorie = :categorie')
               ->setParameter('categorie', $categorie);
        }

        if($admin) $qb->orderBy('a.id', 'DESC');
        else{
            $qb->andWhere('a.isActive =  :isActive')
               ->setParameter('isActive', true);

            $qb->andWhere('a.debut <=  :debut')
               ->setParameter('debut', new \DateTime('now'));

            $qb->orderBy('a.poid', 'DESC');
        }

        return $query = $qb->getQuery()->getResult();
    }

}
